### ISSUE TITLE
But why?

### ISSUE THREAD

**Issue by ZeroXFFF1** [xoreaxeaxeax/movfuscator#13]

**Comment by sigtau** [comment]
I think the better question is "why not?"

Among other possibilities such as making it significantly more difficult to reverse engineer assembly generated by this compiler, it's hilarious to a lot of people.  Then there's the whole "esosteric programming languages exist too" argument, adding more to the "why not?" part.

I'm sure it would a nontrivial task to write a de-obfuscator that searches for MOV patterns that correspond to the appropriate x86 instruction, and maybe equally as fun to write.

**Comment by incertia** [comment]
There is actually a partial demovfuscator [in progress](https://github.com/kirschju/demovfuscator)

**Comment by xoreaxeaxeax** [comment]
See the F.A.Q.
