### ISSUE TITLE
cannot find -lgcc -lc -lm

### ISSUE THREAD

**Issue by dzonerzy** [xoreaxeaxeax/movfuscator#16]
Whenever I try to compile something i got this:

```
/usr/bin/ld: impossibile trovare -lgcc
/usr/bin/ld: impossibile trovare -lc
/usr/bin/ld: impossibile trovare -lm
```

**Comment by xoreaxeaxeax** [comment]
I think this usually means you need to install 32 bit libraries (e.g. apt-get install libc6-dev-i386).  Let me know if that doesn't fix it.
