### ISSUE TITLE
arm, mips, and asic?

### ISSUE THREAD

**Issue by Elmapul** [xoreaxeaxeax/movfuscator#20]
hi, im not an hardware expert by any means, i saw your presentations on black hat about how you can run any program using only mov instructions, and i'm curious:
this principle aply to any processor or its an x86 only thing?

its possible to build an processor with only the mov instruction?
i heard that build an processor with a lot of instructions and reduce its size is complex ,its smarter focus on an small set of instrctions running fast than try to make tons of instructions and end up with something harder to reduce the size to improve the clock.
so maybe an asic that only does mov instructions could be faster than an traditional computer cpu?

**Comment by vido89** [comment]
1. It apply to any processor
2. It is possible to build it
3. No it is not faster is slower because you need to use many more move instructions to achice some result

**Comment by Elmapul** [comment]
i see, thanks =)

**Comment by dnffabs** [comment]
I want to build the corresponding movfuscator on arm architecture, do I also use mov instructions, or do I need other instructions? What should I do accordingly
