### ISSUE TITLE
./check.sh failed ...

### ISSUE THREAD

**Issue by narutocanada** [xoreaxeaxeax/movfuscator#22]
validation/aes/test.c:101: illegal statement termination
validation/aes/test.c:101: skipping `struct'
validation/aes/test.c:101: undeclared identifier `AES_ctx'
validation/aes/test.c:101: warning: expression with no effect elided
validation/aes/test.c:101: syntax error; found `ctx' expecting `;'
validation/aes/test.c:101: undeclared identifier `ctx'
validation/aes/test.c:101: warning: expression with no effect elided
validation/aes/test.c:102: warning: type error in argument 1 to `AES_init_ctx'; found `pointer to int' expected `pointer to struct AES_ctx'
validation/aes/test.c:106: warning: type error in argument 1 to `AES_ECB_encrypt'; found `pointer to int' expected `pointer to struct AES_ctx'

M/o/Vfuscation failed.

maybe the have changed the source code at https://github.com/kokke/tiny-AES128-C
I think you should include a version that worked ... (for all external stuff too, they might get changed)

**Comment by xoreaxeaxeax** [comment]
Fixed, thanks.
