### ISSUE TITLE
Dictionary für equalities

### ISSUE THREAD

**Issue by GAFO** [xoreaxeaxeax/movfuscator#9]
Hello there,
its not realy an issue with your compiler, its more a question if 
you would share the equality dictionary for e.g.  add <-> mov, comp <->mov  
etc

At the end I came to the result that it would be interesting to build such a thing for windows as well.
But instead of making a real compiler, I tought more about writing an translator, which reads the
executeable opcodes, translates them and writes a new executeable. On this way its possible to use 
good compilers which already exist and apply the mov-only theory

,greetings

**Comment by xoreaxeaxeax** [comment]
These lookup tables can be found in movfuscator.c; they are automatically generated by preprocessor macros.  By pulling out the macros, you can get the tables.
